### ALL Todos
GET http://localhost:5000/todos

### GET a todo
GET http://localhost:5000/todo/21

### POST a todo
POST http://localhost:5000/todos
Content-Type: application/json

{
    "description": "random random aja"
}

### PUT a todo (UPDATE)
PUT http://localhost:5000/todo/21
Content-Type: application/json

{
    "description": "opera van jawa"
}

### delete a todo
DELETE http://localhost:5000/todo/23